### PR TITLE
ndk 22.9.25

### PR DESCRIPTION
**Pull request by jon-nokia**
#### Why I did it
Eliminate THERMAL HIGH CURRENT TEMP logging
Fix TransceiverMgr CollectAdminTech

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by gechiang** [comment]
@jon-nokia , is this PR ready or still needs to be under draft mode?

**Comment by jon-nokia** [comment]
> @jon-nokia , is this PR ready or still needs to be under draft mode?

Nokia Test just gave thumbs up.  Now ready to go.  Thanks!

**Review by judyjoseph — APPROVED** [review]

**Comment by rlhui** [comment]
@gechiang , @judyjoseph , reminder to have msft ado for this.

**Comment by gechiang** [comment]
> @gechiang , @judyjoseph , reminder to have msft ado for this.

MSFT ADO: 27350593

**Pull request merged**
