### PR TITLE
ndk 22.9.21

### PR DESCRIPTION
**Pull request by jon-nokia**
#### Why I did it
1) Modify code on the Linecard to detect if Supervisor is ungraceful reboot or removal,  If BDB hardware checking is missing 3 times,  Linecard will reboot itself.
2) Add function to handle the GRPC call to disable all SFPs which provide the capability to the linecard to disable all SFP when linecard is reboot.
3) Added delay to start the sr_dev_mgr on Supervisor to make sure the linecard shutdown all SFPs on the down path when both linecards and Supervisor are rebooting. 
4) Better handling of SFP module read failure and ensure minimum time in reset on SW reset request
5) Added thermal logging improvement.
6) Modified the Supervisor to call "sudo reboot" when the reboot request is from PMON API
7) Fix the reboot-cause history issue which is caused by the change of determine-reboot-cause.service
8) Fix all-modules shutdown

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
Also to 202205, https://github.com/Azure/sonic-buildimage-msft/pull/196

### CODE REVIEW

**Review by gechiang — APPROVED** [review]

**Comment by gechiang** [comment]
@jon-nokia Is there any dependency of this new NDK drop?  Any other PR also needs to be picked up or this is a standalone PR?

**Comment by jon-nokia** [comment]
> @jon-nokia Is there any dependency of this new NDK drop? Any other PR also needs to be picked up or this is a standalone PR?

It should be merged with https://github.com/sonic-net/sonic-buildimage/pull/17378

**Comment by gechiang** [comment]
> > @jon-nokia Is there any dependency of this new NDK drop? Any other PR also needs to be picked up or this is a standalone PR?
> 
> It should be merged with [sonic-net/sonic-buildimage#17378](https://github.com/sonic-net/sonic-buildimage/pull/17378)

Thanks @jon-nokia !
knowing that it is not possible to merge both at the same time.  which one should be merged first to avoid any breakage/regression whether it be build time or run time?

**Comment by judyjoseph** [comment]
@jon-nokia @mlok-nokia  could you update the PR summary, as we have diverged a lot from the original design.
Also please update when it is ready for review/merge

**Comment by jon-nokia** [comment]
> @jon-nokia @mlok-nokia could you update the PR summary, as we have diverged a lot from the original design. Also please update when it is ready for review/merge

Hi @judyjoseph - PR summary has been updated and these are ready to be integrated.  Thanks.

**Comment by mlok-nokia** [comment]
> > @jon-nokia @mlok-nokia could you update the PR summary, as we have diverged a lot from the original design. Also please update when it is ready for review/merge
> 
> Hi @judyjoseph - PR summary has been updated and these are ready to be integrated. Thanks.

This PR should be merged with https://github.com/sonic-net/sonic-buildimage/pull/17483.

**Comment by judyjoseph** [comment]
@mlok-nokia "If BDB hardware checking is missing 3 times" -- what is the interval in which we check this.
So this is in addition to the 4 times check for heartbeat  ( with interval of 10 sec ) ?

**Comment by mlok-nokia** [comment]
> @mlok-nokia "If BDB hardware checking is missing 3 times" -- what is the interval in which we check this. So this is in addition to the 4 times check for heartbeat ( with interval of 10 sec 
The interval is 10 seconds.   The heartbeat checking and BDB check happens at the same time.

**Comment by judyjoseph** [comment]
Is the default log level DEBUG ? @mlok-nokia - Changing to DEBUG in this commit https://github.com/Nokia-ION/ndk/commit/c074eef1f9f0281328ab8050fd6527014ff4fa55 ( line num: 258)  will it be printable data ?

**Review by judyjoseph — APPROVED** [review]

**Comment by mlok-nokia** [comment]
> Is the default log level DEBUG ? @mlok-nokia - Changing to DEBUG in this commit [Nokia-ION/ndk@c074eef](https://github.com/Nokia-ION/ndk/commit/c074eef1f9f0281328ab8050fd6527014ff4fa55) ( line num: 258) will it be printable data ?

The log level is info. Let me add @snider-nokia to comment.

**Comment by mlok-nokia** [comment]
> > > @jon-nokia Is there any dependency of this new NDK drop? Any other PR also needs to be picked up or this is a standalone PR?
> > 
> > 
> > It should be merged with [sonic-net/sonic-buildimage#17378](https://github.com/sonic-net/sonic-buildimage/pull/17378)
> 
> Thanks @jon-nokia ! knowing that it is not possible to merge both at the same time. which one should be merged first to avoid any breakage/regression whether it be build time or run time?

In order to functioning correctly,  both are need to build in the same image.  Either one is merged first won't break the build

**Comment by snider-nokia** [comment]
> > Is the default log level DEBUG ? @mlok-nokia - Changing to DEBUG in this commit [Nokia-ION/ndk@c074eef](https://github.com/Nokia-ION/ndk/commit/c074eef1f9f0281328ab8050fd6527014ff4fa55) ( line num: 258) will it be printable data ?
> 
> The log level is info. I think it is printable data, but it could be encoded. Let me add @snider-nokia to this message

Log level is automatically defaulted to INFO level during NDK bringup.  After that time, log level DEBUG output will only be seen if NDK logging level has been subsequently raised dynamically (by operator intervention) to DEBUG level.  When line 258 is hit (if logging is at DEBUG level) then the data will be printed as a string of hex bytes.

**Comment by snider-nokia** [comment]
@judyjoseph, With NDK version 22.9.20 we have discerned a problem in test whereby oper-up 400G interfaces are not correctly shut down at LC reboot time on the way down (that is currently not occurring until LC is on the way back up again).  100G interfaces do go down timely when LC is on the way down for reboot.

We have corrected this issue and will begin OC testing with this fix this evening (build just completed and tests will be fired up shortly).  You are thus going to need NDK 22.9.21 in order to have this functionality corrected (400G interfaces forced down timely at LC reboot time).

**Comment by mlok-nokia** [comment]
@judyjoseph  We have verified the NDK 22.9.21 works fine and this PR is ready for merge.  Thanks.

**Comment by rlhui** [comment]
also tagging @deepak-singhal0408 on this one.

**Pull request merged**
